### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by serverworm** [mishakorzik/termux-sms-bomber300#3]
When entering the command "python SMSBomber300.py" 
an error occurs 
"python: can't open file '/data/data/com.termux/files/home/SMS-Bomber-300-Free/SMSBomber300.pySMSBomber300.py': [Errno 2] No such file or directory"

**Comment by mishakorzik** [comment]
I'm sorry, but the SMS bomber is no longer working.  Because beta testing is closed.  so the repository is not valid, in 1 day I will fix this problem.
